/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.4.1-240
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
  CallParams,
  callFunction,
  registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v2';

// Services

export interface IdentityLinkDIDServiceDef {
  getDIDDocument: (
    did: string,
    callParams: CallParams<'did'>
  ) =>
    | { code: number; data: string; error: string }
    | Promise<{ code: number; data: string; error: string }>;
}
export function registerIdentityLinkDIDService(
  service: IdentityLinkDIDServiceDef
): void;
export function registerIdentityLinkDIDService(
  serviceId: string,
  service: IdentityLinkDIDServiceDef
): void;
export function registerIdentityLinkDIDService(
  peer: FluencePeer,
  service: IdentityLinkDIDServiceDef
): void;
export function registerIdentityLinkDIDService(
  peer: FluencePeer,
  serviceId: string,
  service: IdentityLinkDIDServiceDef
): void;

export function registerIdentityLinkDIDService(...args: any) {
  registerService(args, {
    defaultServiceId: 'identity-link-did-service',
    functions: [
      {
        functionName: 'getDIDDocument',
        argDefs: [
          {
            name: 'did',
            argType: {
              tag: 'primitive',
            },
          },
        ],
        returnType: {
          tag: 'primitive',
        },
      },
    ],
  });
}

// Functions
