/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.3.2-233
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
  ResultCodes,
  RequestFlow,
  RequestFlowBuilder,
  CallParams,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v1';

function missingFields(obj: any, fields: string[]): string[] {
  return fields.filter(f => !(f in obj));
}

// Services

export interface GithubIdentityLinkServiceDef {
  githubRequest: (
    req: { did: string; username: string },
    requestId: string,
    reqPeer: { hasRelayPeer: boolean; peerId: string; relayPeerId: string },
    callParams: CallParams<'req' | 'requestId' | 'reqPeer'>
  ) => void;
  githubVerify: (
    req: { jws: string },
    requestId: string,
    reqPeer: { hasRelayPeer: boolean; peerId: string; relayPeerId: string },
    callParams: CallParams<'req' | 'requestId' | 'reqPeer'>
  ) => void;
}
export function registerGithubIdentityLinkService(
  service: GithubIdentityLinkServiceDef
): void;
export function registerGithubIdentityLinkService(
  serviceId: string,
  service: GithubIdentityLinkServiceDef
): void;
export function registerGithubIdentityLinkService(
  peer: FluencePeer,
  service: GithubIdentityLinkServiceDef
): void;
export function registerGithubIdentityLinkService(
  peer: FluencePeer,
  serviceId: string,
  service: GithubIdentityLinkServiceDef
): void;

export function registerGithubIdentityLinkService(...args: any) {
  let peer: FluencePeer;
  let serviceId: any;
  let service: any;
  if (FluencePeer.isInstance(args[0])) {
    peer = args[0];
  } else {
    peer = Fluence.getPeer();
  }

  if (typeof args[0] === 'string') {
    serviceId = args[0];
  } else if (typeof args[1] === 'string') {
    serviceId = args[1];
  } else {
    serviceId = 'github-identity-link-service';
  }

  // Figuring out which overload is the service.
  // If the first argument is not Fluence Peer and it is an object, then it can only be the service def
  // If the first argument is peer, we are checking further. The second argument might either be
  // an object, that it must be the service object
  // or a string, which is the service id. In that case the service is the third argument
  if (!FluencePeer.isInstance(args[0]) && typeof args[0] === 'object') {
    service = args[0];
  } else if (typeof args[1] === 'object') {
    service = args[1];
  } else {
    service = args[2];
  }

  const incorrectServiceDefinitions = missingFields(service, [
    'githubRequest',
    'githubVerify',
  ]);
  if (!!incorrectServiceDefinitions.length) {
    throw new Error(
      'Error registering service GithubIdentityLinkService: missing functions: ' +
        incorrectServiceDefinitions.map(d => "'" + d + "'").join(', ')
    );
  }

  peer.internals.callServiceHandler.use((req, resp, next) => {
    if (req.serviceId !== serviceId) {
      next();
      return;
    }

    if (req.fnName === 'githubRequest') {
      const callParams = {
        ...req.particleContext,
        tetraplets: {
          req: req.tetraplets[0],
          requestId: req.tetraplets[1],
          reqPeer: req.tetraplets[2],
        },
      };
      resp.retCode = ResultCodes.success;
      service.githubRequest(req.args[0], req.args[1], req.args[2], callParams);
      resp.result = {};
    }

    if (req.fnName === 'githubVerify') {
      const callParams = {
        ...req.particleContext,
        tetraplets: {
          req: req.tetraplets[0],
          requestId: req.tetraplets[1],
          reqPeer: req.tetraplets[2],
        },
      };
      resp.retCode = ResultCodes.success;
      service.githubVerify(req.args[0], req.args[1], req.args[2], callParams);
      resp.result = {};
    }

    next();
  });
}

// Functions
export type GithubRequestArgReq = { did: string; username: string };
export type GithubRequestArgReqPeer = {
  hasRelayPeer: boolean;
  peerId: string;
  relayPeerId: string;
};

export function githubRequest(
  req: GithubRequestArgReq,
  requestId: string,
  reqPeer: GithubRequestArgReqPeer,
  config?: { ttl?: number }
): Promise<void>;
export function githubRequest(
  peer: FluencePeer,
  req: GithubRequestArgReq,
  requestId: string,
  reqPeer: GithubRequestArgReqPeer,
  config?: { ttl?: number }
): Promise<void>;
export function githubRequest(...args: any) {
  let peer: FluencePeer;
  let req: any;
  let requestId: any;
  let reqPeer: any;
  let config: any;
  if (FluencePeer.isInstance(args[0])) {
    peer = args[0];
    req = args[1];
    requestId = args[2];
    reqPeer = args[3];
    config = args[4];
  } else {
    peer = Fluence.getPeer();
    req = args[0];
    requestId = args[1];
    reqPeer = args[2];
    config = args[3];
  }

  let request: RequestFlow;
  const promise = new Promise<void>((resolve, reject) => {
    const r = new RequestFlowBuilder()
      .disableInjections()
      .withRawScript(
        `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                           (call %init_peer_id% ("getDataSrv" "req") [] req)
                          )
                          (call %init_peer_id% ("getDataSrv" "requestId") [] requestId)
                         )
                         (call %init_peer_id% ("getDataSrv" "reqPeer") [] reqPeer)
                        )
                        (call -relay- ("op" "noop") [])
                       )
                       (call reqPeer.$.relayPeerId! ("op" "noop") [])
                      )
                      (xor
                       (call reqPeer.$.peerId! ("github-identity-link-service" "githubRequest") [req requestId reqPeer])
                       (seq
                        (seq
                         (seq
                          (call reqPeer.$.relayPeerId! ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                        )
                        (call -relay- ("op" "noop") [])
                       )
                      )
                     )
                     (seq
                      (seq
                       (call reqPeer.$.relayPeerId! ("op" "noop") [])
                       (call -relay- ("op" "noop") [])
                      )
                      (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                     )
                    )
                `
      )
      .configHandler(h => {
        h.on('getDataSrv', '-relay-', () => {
          return peer.getStatus().relayPeerId;
        });
        h.on('getDataSrv', 'req', () => {
          return req;
        });
        h.on('getDataSrv', 'requestId', () => {
          return requestId;
        });
        h.on('getDataSrv', 'reqPeer', () => {
          return reqPeer;
        });
        h.onEvent('callbackSrv', 'response', args => {});
        h.onEvent('errorHandlingSrv', 'error', args => {
          const [err] = args;
          reject(err);
        });
      })
      .handleScriptError(reject)
      .handleTimeout(() => {
        reject('Request timed out for githubRequest');
      });

    if (config && config.ttl) {
      r.withTTL(config.ttl);
    }

    request = r.build();
  });
  peer.internals.initiateFlow(request!);
  return Promise.race([promise, Promise.resolve()]);
}

export type GithubVerifyArgReq = { jws: string };
export type GithubVerifyArgReqPeer = {
  hasRelayPeer: boolean;
  peerId: string;
  relayPeerId: string;
};

export function githubVerify(
  req: GithubVerifyArgReq,
  requestId: string,
  reqPeer: GithubVerifyArgReqPeer,
  config?: { ttl?: number }
): Promise<void>;
export function githubVerify(
  peer: FluencePeer,
  req: GithubVerifyArgReq,
  requestId: string,
  reqPeer: GithubVerifyArgReqPeer,
  config?: { ttl?: number }
): Promise<void>;
export function githubVerify(...args: any) {
  let peer: FluencePeer;
  let req: any;
  let requestId: any;
  let reqPeer: any;
  let config: any;
  if (FluencePeer.isInstance(args[0])) {
    peer = args[0];
    req = args[1];
    requestId = args[2];
    reqPeer = args[3];
    config = args[4];
  } else {
    peer = Fluence.getPeer();
    req = args[0];
    requestId = args[1];
    reqPeer = args[2];
    config = args[3];
  }

  let request: RequestFlow;
  const promise = new Promise<void>((resolve, reject) => {
    const r = new RequestFlowBuilder()
      .disableInjections()
      .withRawScript(
        `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                           (call %init_peer_id% ("getDataSrv" "req") [] req)
                          )
                          (call %init_peer_id% ("getDataSrv" "requestId") [] requestId)
                         )
                         (call %init_peer_id% ("getDataSrv" "reqPeer") [] reqPeer)
                        )
                        (call -relay- ("op" "noop") [])
                       )
                       (call reqPeer.$.relayPeerId! ("op" "noop") [])
                      )
                      (xor
                       (call reqPeer.$.peerId! ("github-identity-link-service" "githubVerify") [req requestId reqPeer])
                       (seq
                        (seq
                         (seq
                          (call reqPeer.$.relayPeerId! ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                        )
                        (call -relay- ("op" "noop") [])
                       )
                      )
                     )
                     (seq
                      (seq
                       (call reqPeer.$.relayPeerId! ("op" "noop") [])
                       (call -relay- ("op" "noop") [])
                      )
                      (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                     )
                    )
                `
      )
      .configHandler(h => {
        h.on('getDataSrv', '-relay-', () => {
          return peer.getStatus().relayPeerId;
        });
        h.on('getDataSrv', 'req', () => {
          return req;
        });
        h.on('getDataSrv', 'requestId', () => {
          return requestId;
        });
        h.on('getDataSrv', 'reqPeer', () => {
          return reqPeer;
        });
        h.onEvent('callbackSrv', 'response', args => {});
        h.onEvent('errorHandlingSrv', 'error', args => {
          const [err] = args;
          reject(err);
        });
      })
      .handleScriptError(reject)
      .handleTimeout(() => {
        reject('Request timed out for githubVerify');
      });

    if (config && config.ttl) {
      r.withTTL(config.ttl);
    }

    request = r.build();
  });
  peer.internals.initiateFlow(request!);
  return Promise.race([promise, Promise.resolve()]);
}
