version: "3"
services:
  identity-link-service:
    container_name: identity-link-service
    build: .
    restart: "on-failure"
    env_file:
      - .env
  redis:
    container_name: identity-link-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    logging:
      driver: none
